name: "Terraform create EKS Cluster"

on: 
  workflow_dispatch: #this attribute will enable the manual run to the pipeline


jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

  # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    env: 
      ROOT_PATH: '${{github.workspace}}/terraform'
        

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_wrapper: false

      - name: terraform init
        run: |
          echo `pwd`
          echo "** Running Terraform Init**"
          terraform init
        working-directory: ${{ env.ROOT_PATH }}
    
      - name: terraform Plan
        run: |
          echo `pwd`
          echo "** Running Terraform Plan**"
          terraform plan 
        working-directory: ${{ env.ROOT_PATH }}

      - name: terraform Apply
        run: |
          echo `pwd`
          echo "** Running Terraform Apply**"
          terraform apply -auto-approve
        working-directory: ${{ env.ROOT_PATH }}

    
      
